id: P009337
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD88989
  title: དཀར་མཛེས་ཁུལ་རིག་གནས་ལོ་རྒྱུས་ཀྱི་དཔྱད་ཡིག ༼༡༥༽
  author: ''
  volumes:
    f0e0a9dc0c194a8cbcd272a7bb91fe03:
      image_group_id: I2PD18757
      title: ''
      volume_number: 1
      total_pages: 206
