id: I966DE284
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T21:20:32+00:00'
last_modified: '2022-06-08T10:18:04.653967+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD88989
  title: དཀར་མཛེས་ཁུལ་རིག་གནས་ལོ་རྒྱུས་ཀྱི་དཔྱད་ཡིག ༼༡༥༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8865':
      image_group_id: I2PD18757
      title: ''
      total_pages: 206
      order: 1
      base_file: 8865.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
